version: "3"
services:
  develop:
    build:
      context: .
    ports:
      - "8881:8888"
    volumes:
      - ../:/mnt
    entrypoint: bash -c "cd /mnt && jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash"
    stdin_open: true
    container_name: "jdx_dsb_shopify_develop_${USER}"
    tty: true
    env_file:
      - ../.env

